<a href="https://colab.research.google.com/github/deshmukhamol100/DS_practice/blob/main/python/PythonNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install numpy

numpy practice notbook


In [3]:
import numpy as np
np.__version__

'2.0.2'

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
arr=np.array([1,2,3,4])
type(arr)

numpy.ndarray

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.arange(10,20,5,2)

TypeError: Cannot interpret '2' as a data type

In [ ]:
np.zeros(5)#parameter tunning

In [ ]:
np.zeros(5,dtype=int)#hyperparamer tunning

In [ ]:
np.random.rand(10)

In [ ]:
np.random.ranint(10)

In [ ]:
np.randint(10)

In [ ]:
np.zeros([2,3], dtype=int)

In [ ]:
np.zeros([5,10],dtype=int)

# New Section

In [15]:
arr0=np.arange([5:10],dtype=int)
arr0[0:4:2]

SyntaxError: invalid syntax (914877715.py, line 1)

In [16]:
arr0 = np.random.randint(10,40,(10,10))
print(arr0)

[[31 16 22 20 19 11 26 19 22 26]
 [22 22 22 36 12 36 25 26 17 20]
 [24 32 10 17 27 13 22 34 17 33]
 [35 23 10 34 36 28 29 26 17 37]
 [17 12 28 20 39 11 23 30 36 12]
 [35 37 17 35 14 29 18 17 19 28]
 [13 36 24 18 19 39 29 15 32 30]
 [27 35 26 37 31 12 14 21 13 25]
 [38 16 14 32 35 20 16 31 23 26]
 [37 18 25 10 12 17 37 11 33 37]]


In [17]:
arr0[::3]

array([[31, 16, 22, 20, 19, 11, 26, 19, 22, 26],
       [35, 23, 10, 34, 36, 28, 29, 26, 17, 37],
       [13, 36, 24, 18, 19, 39, 29, 15, 32, 30],
       [37, 18, 25, 10, 12, 17, 37, 11, 33, 37]])

In [23]:
arr1 = np.random.randint(1,5,(3,3))
print(arr1)

[[3 3 4]
 [3 2 1]
 [2 3 4]]


In [19]:
arr1[1,2]  --specific value

np.int64(2)

In [20]:
arr1[:2]

array([[3, 3, 2],
       [4, 3, 2]])

reshape

In [37]:
print(arr1)

[[3 3 4]
 [3 2 1]
 [2 3 4]]


In [38]:
arr1[0:2,1:3]

array([[3, 4],
       [2, 1]])

masking or filter in matrix

In [39]:
arr0

array([[31, 16, 22, 20, 19, 11, 26, 19, 22, 26],
       [22, 22, 22, 36, 12, 36, 25, 26, 17, 20],
       [24, 32, 10, 17, 27, 13, 22, 34, 17, 33],
       [35, 23, 10, 34, 36, 28, 29, 26, 17, 37],
       [17, 12, 28, 20, 39, 11, 23, 30, 36, 12],
       [35, 37, 17, 35, 14, 29, 18, 17, 19, 28],
       [13, 36, 24, 18, 19, 39, 29, 15, 32, 30],
       [27, 35, 26, 37, 31, 12, 14, 21, 13, 25],
       [38, 16, 14, 32, 35, 20, 16, 31, 23, 26],
       [37, 18, 25, 10, 12, 17, 37, 11, 33, 37]])

Print the number less than 20

In [41]:
arr0>= 20

array([[ True, False,  True,  True, False, False,  True, False,  True,
         True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True],
       [ True,  True, False, False,  True, False,  True,  True, False,
         True],
       [ True,  True, False,  True,  True,  True,  True,  True, False,
         True],
       [False, False,  True,  True,  True, False,  True,  True,  True,
        False],
       [ True,  True, False,  True, False,  True, False, False, False,
         True],
       [False,  True,  True, False, False,  True,  True, False,  True,
         True],
       [ True,  True,  True,  True,  True, False, False,  True, False,
         True],
       [ True, False, False,  True,  True,  True, False,  True,  True,
         True],
       [ True, False,  True, False, False, False,  True, False,  True,
         True]])

In [42]:
arr0[arr0 < 20 ]

array([16, 19, 11, 19, 12, 17, 10, 17, 13, 17, 10, 17, 17, 12, 11, 12, 17,
       14, 18, 17, 19, 13, 18, 19, 15, 12, 14, 13, 16, 14, 16, 18, 10, 12,
       17, 11])

In [43]:
arr0[arr0>20]

array([31, 22, 26, 22, 26, 22, 22, 22, 36, 36, 25, 26, 24, 32, 27, 22, 34,
       33, 35, 23, 34, 36, 28, 29, 26, 37, 28, 39, 23, 30, 36, 35, 37, 35,
       29, 28, 36, 24, 39, 29, 32, 30, 27, 35, 26, 37, 31, 21, 25, 38, 32,
       35, 31, 23, 26, 37, 25, 37, 33, 37])

In [44]:
arr0[arr0 != 20]

array([31, 16, 22, 19, 11, 26, 19, 22, 26, 22, 22, 22, 36, 12, 36, 25, 26,
       17, 24, 32, 10, 17, 27, 13, 22, 34, 17, 33, 35, 23, 10, 34, 36, 28,
       29, 26, 17, 37, 17, 12, 28, 39, 11, 23, 30, 36, 12, 35, 37, 17, 35,
       14, 29, 18, 17, 19, 28, 13, 36, 24, 18, 19, 39, 29, 15, 32, 30, 27,
       35, 26, 37, 31, 12, 14, 21, 13, 25, 38, 16, 14, 32, 35, 16, 31, 23,
       26, 37, 18, 25, 10, 12, 17, 37, 11, 33, 37])

In [49]:
min(arr0)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()