In [1]:
import numpy as np

In [22]:
np.__version__

'2.4.2'

In [23]:
list = [1,2,3,4,5]
print(list) 

[1, 2, 3, 4, 5]


In [24]:
type(list)

list

In [25]:
arr = np.array(list)
print(arr)

[1 2 3 4 5]


In [26]:
type(arr)

numpy.ndarray

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.random.rand(3,2)

array([[0.82586235, 0.86821542],
       [0.97619851, 0.68311271],
       [0.01558991, 0.87808297]])

In [7]:
np.random.rand(2)

array([0.49718188, 0.09317222])

In [12]:
data = np.random.randint(10,40,(10,10))
print(data)
#row fist and column second

[[25 21 29 27 30 33 35 27 14 24]
 [20 16 29 26 34 18 22 36 19 20]
 [21 33 31 12 36 38 30 29 27 15]
 [24 25 35 22 11 20 10 35 25 35]
 [36 29 14 19 18 38 16 37 35 11]
 [13 23 29 37 37 15 25 37 35 16]
 [37 21 38 14 29 15 19 30 38 16]
 [17 10 39 26 15 17 32 26 12 14]
 [13 10 16 30 11 37 35 31 23 26]
 [15 20 31 39 27 36 11 31 35 18]]


In [21]:
print(data(5:10,) [7:9])

SyntaxError: invalid syntax (599724476.py, line 1)

In [1]:
import numpy as np

# Array creation functions

In [3]:
a= np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
#values from 0 to 10 with step of 2
b = np.arange(0,10,2)#valus from 0 to 10 with step of 2
b

array([0, 2, 4, 6, 8])

In [ ]:
d= np.zeros((2,3))#values of 0 with 2 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
e = np.ones((3,2),dtype=int)#values of 1 with 3 rows and 2 columns
e

array([[1, 1],
       [1, 1],
       [1, 1]])

In [17]:
f =np.eye(4)#values of 1 with 4 rows and 4 columns
#create identity matrix with 4 rows and 4 columns

f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 2.Array Manipulation function

In [ ]:
#reshape the array
a1 = np.array([1,2,3])
reshaped_a1 = np.reshape(a1,(3,1))#reshape the array a1 to have 3 rows and 1 column
reshaped_a1


array([[1],
       [2],
       [3]])

In [27]:
f1 = np.array([[1,2,3],[4,5,6]])
falternate_f1 = np.ravel(f1) # ravel the array f1 to a 1D array
falternate_f1

array([1, 2, 3, 4, 5, 6])

In [29]:
e1 = np.array([[1,2,3],[4,5,6]])
tranposed_e1 = np.transpose(e1) # transpose the array e1
tranposed_e1

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
a1 = np.array([1,2,3])
a2 =np.array([4,5,6 ])
stacked_a2 = np.vstack((a1,a2)) # stack the array a2 on top of itself
stacked_a2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a1 = np.array([1,2,3])
a2 =np.array([4,5,6 ])
stacked_a2 = np.hstack((a1,a2)) # stack the array a2 on top of itself
stacked_a2

array([1, 2, 3, 4, 5, 6])